version: '3'

services:
  database:
    image: postgres
    ports:
      - '5432:5432'
    container_name: funimation
    restart: always 
    volumes:
      - postgres-disk:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 'brabra'
      POSTGRES_DB: funimation


volumes:
  postgres-disk: